name: triage
description: Automatically triage issues

branding:
  icon: zap
  color: gray-dark

inputs:
  project_column:
    description: >
      The org-level project and column within that project to send new issues and PRs to. Separate with a slash.
      
      Example: "Planning/Triage" for the "Triage" column of the "Planning" project
    required: true

runs:
  using: "composite"
  steps:
    - run: python3 -m pip install --upgrade pip
      shell: bash
    - run: python3 -m pip install -qqq githubgql pyyaml
      shell: bash
    - run: $GITHUB_ACTION_PATH/src/triage "${{ inputs.project_column }}"
      shell: bash
    - run: bash -c "env | sort"
      shell: bash
    - run: cat $GITHUB_EVENT_PATH
      shell: bash
